# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c67e16db43c1606e286a3a8137507b1fc35b7bcf4a5d3ac072bdc7131ee2afa3a5ceda7aa0f40921e260de5cd1662f8a975bcc11e9d7ba2fc088b642e60564a

test:
  secret_key_base: fa14ebaf26a4000afa7cf56e3d9a6bd1c6ffa6568da443aad454d9bb91e66bf6faf889d57c7a74c22f7115087a5cae1f9cdd9e318bdc64a731c17745fdf99038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
